### ISSUE TITLE
look at new data sets or scrub the current data set

### ISSUE THREAD

**Issue by chris-aqui** [Waste-Relations/Waste-Relations#23]
Uzair recommends we scrub the data to get clean consistent data or look for new data.

**Comment by chris-aqui** [comment]
i will attempt to scrub data on Friday night using Bryce pseudocode example

const pieceOTrash = {
	name: '',
	category: '',
	sub_category: '',
	description: ''
}

const outArray = [];

for (trash of trashes) {
	const tempArray = trash.keywords.split(', ')
	for (const i = 0; i < tempArray.length; i++) {
		pieceOTrash.name = tempArray[i].toTitleCase();
		pieceOTrash.category = trash.category;
		pieceOTrash.sub_category = titleTransform(trash.title);
		// Make sure to define trash transform somehwere!!!
		pieceOTrash.description = trash.description;
		this.outArray.push(pieceOTrash);
	}
}

console.log(outArray);

**Comment by andretqt** [comment]
currently looking for datasets but so far the data set we have (i.e. waste disposal) is the only one of its kind. Other canadian cities have a waste wizard that is powered through some third party application (e.g https://recollect.net/). It may be better to scrub what we have

**Comment by chris-aqui** [comment]
@andretqt  i'm going to push the code i have so far. 
i've run into some issues maybe you can take a look.

**Comment by chris-aqui** [comment]
@andretqt 
[repo location](https://github.com/christine-aqui/scrub-a-dub-dub)

**Comment by andretqt** [comment]
scruber code seems to work as desired on my end.  @christine-aqui  Test it out

**Comment by chris-aqui** [comment]
@andretqt  Great work. 
Tested and verified data.
