### ISSUE TITLE
Initial Database data

### ISSUE THREAD

**Issue by chris-aqui** [Waste-Relations/Waste-Relations#4]
- Create Schema
- Create initial seed data

**Comment by LisaFreedman** [comment]
Schema created for waste - data successfully imported into table
Shema created for waste depots - data will be imported by August 6
Schema created for donations - requires additional research to ensure we have a robust collection of donations from across the city - data will be imported by August 7

**Comment by LisaFreedman** [comment]
All data created
Waste data imported
Meeting Uzair at early office hours tomorrow as bug importing two small tables but I can use direct insert into if all else fails
